# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: ${env:SERVERLESS_ORG}
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: ${env:SERVERLESS_APP}
# "service" is the name of this project. This will also be added to your AWS resource names.
service: ${env:SERVERLESS_SERVICE}

provider:
  name: aws
  runtime: nodejs20.x
  region: ${env:AWS_REGION}
  iam:
    role: ${env:AWS_ROLE}

functions:
  Signup:
    handler: functions/user/Signup/index.handler
    events:
      - httpApi:
          path: /auth/signup
          method: post

resources:
  Resources:
    firstTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${env:TABLE_USER}
        AttributeDefinitions:
          - AttributeName: username
            AttributeType: S
        KeySchema:
          - AttributeName: username
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
